<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Estacion', 'doctrine');

/**
 * BaseEstacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $identificador
 * @property string $nombre_estacion
 * @property float $latitud
 * @property float $longitud
 * @property integer $altura
 * @property integer $distancia_al_mar
 * @property enum $region
 * @property string $imagen
 * @property string $color
 * @property integer $alto
 * @property integer $ancho
 * @property Doctrine_Collection $Fotos
 * @property Doctrine_Collection $Mediciones
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method integer             getIdentificador()    Returns the current record's "identificador" value
 * @method string              getNombreEstacion()   Returns the current record's "nombre_estacion" value
 * @method float               getLatitud()          Returns the current record's "latitud" value
 * @method float               getLongitud()         Returns the current record's "longitud" value
 * @method integer             getAltura()           Returns the current record's "altura" value
 * @method integer             getDistanciaAlMar()   Returns the current record's "distancia_al_mar" value
 * @method enum                getRegion()           Returns the current record's "region" value
 * @method string              getImagen()           Returns the current record's "imagen" value
 * @method string              getColor()            Returns the current record's "color" value
 * @method integer             getAlto()             Returns the current record's "alto" value
 * @method integer             getAncho()            Returns the current record's "ancho" value
 * @method Doctrine_Collection getFotos()            Returns the current record's "Fotos" collection
 * @method Doctrine_Collection getMediciones()       Returns the current record's "Mediciones" collection
 * @method Estacion            setId()               Sets the current record's "id" value
 * @method Estacion            setIdentificador()    Sets the current record's "identificador" value
 * @method Estacion            setNombreEstacion()   Sets the current record's "nombre_estacion" value
 * @method Estacion            setLatitud()          Sets the current record's "latitud" value
 * @method Estacion            setLongitud()         Sets the current record's "longitud" value
 * @method Estacion            setAltura()           Sets the current record's "altura" value
 * @method Estacion            setDistanciaAlMar()   Sets the current record's "distancia_al_mar" value
 * @method Estacion            setRegion()           Sets the current record's "region" value
 * @method Estacion            setImagen()           Sets the current record's "imagen" value
 * @method Estacion            setColor()            Sets the current record's "color" value
 * @method Estacion            setAlto()             Sets the current record's "alto" value
 * @method Estacion            setAncho()            Sets the current record's "ancho" value
 * @method Estacion            setFotos()            Sets the current record's "Fotos" collection
 * @method Estacion            setMediciones()       Sets the current record's "Mediciones" collection
 * 
 * @package    innova_versionado
 * @subpackage model
 * @author     Rodrigo Muñoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEstacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('estacion');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('identificador', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('nombre_estacion', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('latitud', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('longitud', 'float', null, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('altura', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('distancia_al_mar', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('region', 'enum', 55, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'I REGIÓN DE TARAPACÁ',
              1 => 'II REGIÓN DE ANTOFAGASTA',
              2 => 'III REGIÓN DE ATACAMA',
              3 => 'IV REGIÓN DE COQUIMBO',
              4 => 'V REGIÓN DE VALPARAISO',
              5 => 'VI REGIÓN DEL LIBERTADOR GENERAL BERNARDO O\'HIGGINS',
              6 => 'VII REGIÓN DEL MAULE',
              7 => 'VIII REGIÓN DEL BÍO - BÍO',
              8 => 'IX REGIÓN DE LA ARAUCANÍA',
              9 => 'X REGIÓN DE LOS LAGOS',
              10 => 'XI REGIÓN AYSÉN DEL GENERAL CARLOS IBÁÑEZ DEL CAMPO',
              11 => 'XII REGIÓN DE MAGALLANES Y LA ANTÁRTICA CHILENA',
              12 => 'RM REGIÓN METROPOLITANA',
              13 => 'XIV REGION DE LOS RÍOS',
              14 => 'XV REGIÓN DE ARICA Y PARINACOTA',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 55,
             ));
        $this->hasColumn('imagen', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('color', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => 'white',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('alto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '16',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ancho', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '16',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Fotos', array(
             'local' => 'id',
             'foreign' => 'estacion'));

        $this->hasMany('Mediciones', array(
             'local' => 'id',
             'foreign' => 'estacion'));
    }
}