<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mediciones', 'doctrine');

/**
 * BaseMediciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $tipo
 * @property enum $mes
 * @property integer $anio
 * @property integer $estacion
 * @property float $valor
 * @property string $observaciones
 * @property Estacion $Estacion
 * 
 * @method integer    getId()            Returns the current record's "id" value
 * @method enum       getTipo()          Returns the current record's "tipo" value
 * @method enum       getMes()           Returns the current record's "mes" value
 * @method integer    getAnio()          Returns the current record's "anio" value
 * @method integer    getEstacion()      Returns the current record's "estacion" value
 * @method float      getValor()         Returns the current record's "valor" value
 * @method string     getObservaciones() Returns the current record's "observaciones" value
 * @method Estacion   getEstacion()      Returns the current record's "Estacion" value
 * @method Mediciones setId()            Sets the current record's "id" value
 * @method Mediciones setTipo()          Sets the current record's "tipo" value
 * @method Mediciones setMes()           Sets the current record's "mes" value
 * @method Mediciones setAnio()          Sets the current record's "anio" value
 * @method Mediciones setEstacion()      Sets the current record's "estacion" value
 * @method Mediciones setValor()         Sets the current record's "valor" value
 * @method Mediciones setObservaciones() Sets the current record's "observaciones" value
 * @method Mediciones setEstacion()      Sets the current record's "Estacion" value
 * 
 * @package    innova_versionado
 * @subpackage model
 * @author     Rodrigo Muñoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMediciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mediciones');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('tipo', 'enum', 21, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Cloruro',
              1 => 'Sulfato',
              2 => 'Humidificacion',
              3 => 'Velocidad_aluminio',
              4 => 'Velocidad_acero',
              5 => 'Velocidad_cobre',
              6 => 'Velocidad_galvanizado',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 21,
             ));
        $this->hasColumn('mes', 'enum', 10, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Enero',
              1 => 'Febrero',
              2 => 'Marzo',
              3 => 'Abril',
              4 => 'Mayo',
              5 => 'Junio',
              6 => 'Julio',
              7 => 'Agosto',
              8 => 'Septiembre',
              9 => 'Octubre',
              10 => 'Noviembre',
              11 => 'Diciembre',
             ),
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 10,
             ));
        $this->hasColumn('anio', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('estacion', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('valor', 'float', 18, array(
             'type' => 'float',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 18,
             ));
        $this->hasColumn('observaciones', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estacion', array(
             'local' => 'estacion',
             'foreign' => 'id'));
    }
}