<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Fotos', 'doctrine');

/**
 * BaseFotos
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $estacion
 * @property string $foto
 * @property string $descripcion
 * @property Estacion $Estacion
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method integer  getEstacion()    Returns the current record's "estacion" value
 * @method string   getFoto()        Returns the current record's "foto" value
 * @method string   getDescripcion() Returns the current record's "descripcion" value
 * @method Estacion getEstacion()    Returns the current record's "Estacion" value
 * @method Fotos    setId()          Sets the current record's "id" value
 * @method Fotos    setEstacion()    Sets the current record's "estacion" value
 * @method Fotos    setFoto()        Sets the current record's "foto" value
 * @method Fotos    setDescripcion() Sets the current record's "descripcion" value
 * @method Fotos    setEstacion()    Sets the current record's "Estacion" value
 * 
 * @package    innova_versionado
 * @subpackage model
 * @author     Rodrigo Muñoz
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFotos extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('fotos');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('estacion', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('foto', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Estacion', array(
             'local' => 'estacion',
             'foreign' => 'id'));
    }
}