generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Fotos
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          fotos
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    
        title: Listado de Imagenes
        display: [id, estacion, _foto, descripcion]
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
